### ISSUE TITLE
Python 3.10 ошибка с get_user()

### ISSUE THREAD

**Issue by YaFlay** [teleport2/Py-SPW#2]
У меня есть вот такой код:
` 
if pyspw.SpApi.get_user(discord_id=(inter.author.id)):
    await inter.response.send_message('Done', ephemeral=True)
else:
    await inter.response.send_message('None.', ephemeral=True)
`
(код временный, для дискорда)
и он выдает ошибку 
![image](https://user-images.githubusercontent.com/93622229/216050919-dff513b3-566d-4bab-b74d-831a84cb89ac.png)
я пробовал сначала через pyspw.api.get_access(discord_id), но он выдавал ошибку. Я покопался в файлах библиотеки, и понял что документация устаревшая, начал использовать SpApi, но он тоже выдает ошибку, но теперь уже требует какой-то self

**Comment by YaFlay** [comment]
с токеном проблема была

**Comment by teleport2** [comment]
Здраствуйте, я рад, что вы решили проблему. А вы не могли бы сказать где документация устаревшая?

**Comment by YaFlay** [comment]
> Здраствуйте, я рад, что вы решили проблему. А вы не могли бы сказать где документация устаревшая? У меня складывается впечатление, что вы пытались вызвать методы без инициализации класса, что невозможно и вызывает ошибку.

в вики написано об использовании к примеру get_user через api, на что питон ругается, а если заменить api на SpApi(SpApi.get_user(discord_id)), то все работает, если не считать отсутствие токена проблемой

**Comment by teleport2** [comment]
Под `api` подразумевается объект класса, который в свою очередь надо ранее инициализировать под переменной `api`

**Comment by YaFlay** [comment]
> Под `api` подразумевается объект класса, который в свою очередь надо ранее инициализировать под переменной `api`

А, понял, я просто нигде это не нашел в документации
