### ISSUE TITLE
В последнее время не работает библиотека

### ISSUE THREAD

**Issue by YaFlay** [teleport2/Py-SPW#3]
Не работает библиотека, ругается на JSON.DecodeError

**Comment by teleport2** [comment]
Это антиддос сайта, который возращает html, вместо json. В Цитирую администраторов сайта:

> Новости на счёт API сайта, с недавнего времени наблюдаются проблемы с подключением и использованием эндпоинтов API. Связано с участившимися DoS и DDoS атаками именно через API. Это временная мера, возможно, в дальнейшем ограничения будут сняты. 
Если сейчас вам очень сильно хочется использовать API, вы можете написать на почту поддержки сайта - описание вашего проекта, и белый IP вашего хостинга (который мы сможем добавить в вайт лист anti-ddos для нормального использования API)
